### ISSUE TITLE
Make login/signup page

### ISSUE THREAD

**Issue by bhupesh98** [opencodeiiita/GrepIt-Frontend#1]
Create the signup/login page, just place, and style the components. You can add a suitable style to the text input fields. You can reference the attached image for the structure of the signup page, a relevant background image will be placed on the left side.
It is recommended to use tailwind css along with antd design for, if unable to do with that, it is acceptable using other techniques, just make sure it is responsive. We are although mainly focussing on desktop design.

![login](https://github.com/opencodeiiita/GrepIt-Frontend/assets/70364481/b6db414e-56aa-44c4-b41a-c0f925a5ec11)

Work on [here](https://github.com/opencodeiiita/GrepIt-Frontend/blob/master/src/pages/Home.jsx) while making relevant components in the components folder.

**Comment by TheDivineAurora** [comment]
claim

**Comment by k7aditya** [comment]
claim

**Comment by rebornstar1** [comment]
claim

**Comment by bhupesh98** [comment]
@TheDivineAurora assigned!

**Comment by Nupur513** [comment]
claim

**Comment by imsushmitha-13** [comment]
claim

**Comment by bhupesh98** [comment]
Once, it is assigned, you can stop claiming messages. And please tag the mentors for that for faster responses.

**Comment by vineeshmittal1** [comment]
claim

**Comment by koteshb25** [comment]
Claim #3

**Comment by bhupesh98** [comment]
> Claim #3

This issue is already done, posting new issues soon
