### ISSUE TITLE
User Card Implementation!

### ISSUE THREAD

**Issue by shashankpatil28** [opencodeiiita/GrepIt-Frontend#10]
### we have an exciting challenge for you to enhance GrepIt's user interface. 

**Task Details:**

Your task is to create a User Card component positioned at the top left of the home page. Here are the specific details.

**#Details**

1. Develop a component that showcases a Profile photo and a placeholder Profile Name. Take input details as a prop.
2. On smaller devices, it should gracefully shrink to display only the Profile photo.
3. Implement an onClick event on the component. When clicked, it should trigger a drop-down containing options for "View Profile" and "Logout"
4. Implement a redirect so that clicking 'View Profile' directs the user to the empty '/profile' route.

> File Location: Write the component in src/components/UserCard.jsx.
> Router Placement: Integrate the component into the app router with the path '/home'.

Ready to tackle this? Comment below to **claim** the challenge!

**Comment by rnavaneeth992** [comment]
claim

**Comment by rnavaneeth992** [comment]
claim

**Comment by AngadManroy** [comment]
Claim

**Comment by kushal7201** [comment]
claim

**Comment by atharva0192** [comment]
claim

**Comment by Nandinig24** [comment]
Claim

**Comment by Xaverick** [comment]
claim

**Comment by parimal-10** [comment]
claim

**Comment by shashankpatil28** [comment]
@rnavaneeth992 Congrats, you have claimed the issue. Follow the details properly and do the work ASAP. for any query feel free to ask on Discord.

**Comment by chiragmalik2612** [comment]
claim
