### ISSUE TITLE
useAuth: The Login Gatekeeper

### ISSUE THREAD

**Issue by bhupesh98** [opencodeiiita/GrepIt-Frontend#11]
Task Details:
Your mission is to create a custom useAuth hook, a powerful tool for managing user authentication. Here are the specific details:

## Details
Craft a useAuth hook that utilizes useContext to determine the login status based on the presence of a special token in localStorage.
When the cherished token exists, let useAuth boldly declare, "Login granted!" with a true value.
In the absence of the token, let it softly murmur, "Not logged in" with a false value.
Ensure graceful handling of scenarios where the token is missing—no crashes allowed.
Customize the hook to be able to seamlessly integrate with your project's existing authentication setup.
Keep the implementation concise and purpose-driven.

## File Location:
Write this dynamic component in `src/hooks/useAuth.jsx`.

Feel free to ask regarding any confusion in the given task.

Are you ready to embark on this challenge and unlock the authentication prowess of useAuth for GrepIt? Comment below to claim the task!

**Comment by rnavaneeth992** [comment]
claim

**Comment by bhupesh98** [comment]
Heyy @rnavaneeth992, You are already working on a task in this repo. Kindly complete the issue before claiming another one.

**Comment by kushal7201** [comment]
claim @bhupesh98

**Comment by Rohit-110** [comment]
claim

**Comment by bhupesh98** [comment]
@kushal7201  Assigned!

**Comment by Nandinig24** [comment]
Claim

**Comment by QuantTitan** [comment]
claim

**Comment by Rohit-110** [comment]
claim
