### ISSUE TITLE
Create a Room Card Component

### ISSUE THREAD

**Issue by shashankpatil28** [opencodeiiita/GrepIt-Frontend#19]
### Your mission is to craft a CreateRoom component for quiz creation in GrepIt. Here are the specifics:

**Task Details:**

Your task is to create a **CreateRoom** named component that contains various input boxes. Details are given below.

**#Details**

1. Refer to the provided design and feel free to inject your creativity, which may be recognized separately if exceptional.
2. Ensure the input boxes align with their respective types. For example, a scheduled quiz must include time and date inputs. Utilize AntDesign components effectively.
3. The "Create Quiz" button should navigate to the '/quiz' route.
4. The "Get Link to Room" button must trigger a backend request to generate a link based on the filled data.
5. Make the component responsive for a seamless user experience on various devices.

![image](https://github.com/opencodeiiita/GrepIt-Frontend/assets/122175701/73c72978-5728-4c25-8183-4009c6204ab8)

- > File Location: Write the component in src/components/createRoom.jsx

- > Router Placement: Integrate the component into the app router with the path '/home' and place it properly at the center-left side.

Claim this challenge by commenting below!

**Comment by rnavaneeth992** [comment]
claim

**Comment by shashankpatil28** [comment]
Team, please include success/error messages upon returning from the '/quiz' route as per given. Also, prevent room link generation before creating a quiz. Utilize appropriate hooks and props for functionality. Thank you.

**Comment by shashankpatil28** [comment]
@rnavaneeth992 go through the details once again and make it to completion ASAP. for any discussion related to the task, ping me on Discord.
