### ISSUE TITLE
Design the web-app logo for GrepIt

### ISSUE THREAD

**Issue by bhupesh98** [opencodeiiita/GrepIt-Frontend#2]
Grepit is a quizzing platform that is to be built for quizzing and competition with peers. Design a logo for this project that depicts the same idea.
Enter your github account and attach the figma link in the [designs.json](https://github.com/opencodeiiita/GrepIt-Frontend/blob/master/public/design.json) file.

**This issue is open-for-all and there is no need to claim. Work on the issue and submit a PR.**

**Comment by DIWAKARKASHYAP** [comment]
claim
