### ISSUE TITLE
Design Task on the Glass-Morfism

### ISSUE THREAD

**Issue by shashankpatil28** [opencodeiiita/GrepIt-Frontend#20]
### Your mission is to design a Div having a GlassMorf component inside it. 

**#Details**

1. make a div of 40vh height and width and give the best color/gradient of your choice which is suitable to our grepIt application.
2. inside the div, make a div of 30vh h and w exactly at the center having glass-morphism property. with proper blurness.
3. you have to share the screenshot of the design and the proper Code of the component in the glassMorf.json file in the below format.

**Glass-Morfism resources are updated on Discord.
The best 5 to 6 PRs will get merged.**
```
{
     "githubid" = "your id",
     "ss link to div" = "link1",
     "ss link to code" = "link2"
},
```

**No need to Claim this challenge, It is open to all.**

**Comment by kushal7201** [comment]
c

**Comment by Rohit-110** [comment]
c

**Comment by shashankpatil28** [comment]
@everyone no need to claim. it is open for all.

**Comment by shashankpatil28** [comment]
Kindly follow that the code must have tailwind for styling purpose.

**Comment by kushal7201** [comment]
@shashankpatil28  Should the code be screenshot or proper file link?

**Comment by shashankpatil28** [comment]
> @shashankpatil28 Should the code be screenshot or proper file link?
anyone
