### ISSUE TITLE
Display the Room Link!

### ISSUE THREAD

**Issue by shashankpatil28** [opencodeiiita/GrepIt-Frontend#22]
### Task:
**You aim to make a Card component for the Displaying room link. The reference design is linked below.**

**Details are as follows ->**
1. Responsiveness. 
2. You can make it on your design.
3. Use of AntDesign is mandatory. also, give the card a proper shadow.

the reference design is here. you may add on design from your side too.

![image](https://github.com/opencodeiiita/GrepIt-Frontend/assets/122175701/f96f470c-e6c5-404e-9f37-66ff425f68aa)

> component path: src/components/roomLink.jsx
> at the time of PR show the ss for the card instead of placing it in any route.
> 

**Claim the issue by commenting below.**

**Comment by QuantTitan** [comment]
claim

**Comment by Rohit-110** [comment]
@shashankpatil28  claim

**Comment by kushal7201** [comment]
Claim

**Comment by WadadParker** [comment]
claim

**Comment by WadadParker** [comment]
Okay guys, so first you write c to comment first then edit it into claim. Nice, will do this next time

**Comment by shashankpatil28** [comment]
@QuantTitan and @kushal7201 you both have already claimed 3 issues. I cannot assign you to this task for this reason. Happy contributing.

**Comment by amanrubey** [comment]
Claim

**Comment by shashankpatil28** [comment]
> Okay guys, so first you write c to comment first then edit it into the claim. Nice, will do this next time

@WadadParker 
We appreciate your understanding, but after careful consideration, it has been decided not to assign this task due to its repetitive nature. Your cooperation in this regard is valued.

**Comment by shashankpatil28** [comment]
@WadadParker, aim to complete the component within a day.

**Comment by WadadParker** [comment]
As the PR is merged, am unassigning myself so that it does not show I have an extra issue assigned to me, please close this issue as completed

**Comment by bhupesh98** [comment]
> As the PR is merged, am unassigning myself so that it does not show I have an extra issue assigned to me, please close this issue as completed

Once PR is merged, you don't need to unassign yourself for claiming extra task
