### ISSUE TITLE
Beyond the Basics: Crafting an Loader !

### ISSUE THREAD

**Issue by shashankpatil28** [opencodeiiita/GrepIt-Frontend#23]
### Your mission is to create a Loader for GrepIt, utilizing resources available on Discord.

**Task Details:**

1. Develop a Loader Component for the application.
2. Exercise creative freedom in designing the loader, ensuring compatibility with a Dark theme background.
3. Showcase the loader's functionality through a video on Discord during the Pull Request.
4. Ensure proper loader functionality with a critical emphasis on utilizing appropriate React hooks and states.

> File Location: Implement the loader component in src/components/loader.jsx.

**To claim this challenge, kindly leave a comment below! Your dedication to this task is much appreciated.**

**Comment by kushal7201** [comment]
Claim

**Comment by Rohit-110** [comment]
claim

**Comment by Jarviss77** [comment]
claim

**Comment by shashankpatil28** [comment]
@kushal7201 You have already claimed 3 issues Hence we cant assign more issues. Happy Contributing.

**Comment by Karansenpai** [comment]
claim

**Comment by Rohit-110** [comment]
@shashankpatil28 please review and merge
