### ISSUE TITLE
 Grepit Leaderboard Development 

### ISSUE THREAD

**Issue by shashankpatil28** [opencodeiiita/GrepIt-Frontend#30]
### Exciting times at grepit! It's time To make a leaderBoard for the application. 

**Tasks:**

It's time to introduce a leaderboard to our application. Your mission is to craft a responsive leaderboard using the Ant Design UI library. Utilize dummy data, including position, name, UID, and quiz points, integrated seamlessly with Maps and necessary hooks.

**major Details:**

1. Ensure seamless responsiveness across all devices.
2. Place the leaderboard at /leaderboard, prominently centered [ position ].
3. Design must suit User experience as well as possible. Draw inspiration from Dribbble for an exceptional user-centric design.
4. Fetch dummy data from an external REST API. (any of your knowledge).
5. Utilize proper hooks and props for a structured implementation.

> Your commitment to quality work will be duly rewarded.

Comment to claim this impactful issue
Thank you for your valuable contribution! 🌟

**Comment by Rohit-110** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by rnavaneeth992** [comment]
claim

**Comment by WadadParker** [comment]
@shashankpatil28 I would like to work on this issue, but I see that you have assigned this issue to sm1 who is already assigned an issue in this repo

**Comment by Rohit-110** [comment]
@WadadParker I have already opened the pull request of the previous issue assigned to me and i also started on this issue
