### ISSUE TITLE
Link and Play: Grepit's Join Room

### ISSUE THREAD

**Issue by shashankpatil28** [opencodeiiita/GrepIt-Frontend#31]
### Greetings Team!

In the dynamic world of Grepit, we are excited to introduce a sibling component to the Create Room feature – the Join Room component. Here are the key details for your next task:

**📌 Major Details:**

1. Add an input box and a join button to the Join Room component, and feel free to include additional elements for a seamless fit in the home section.
2. Ensure the button navigates the app to the` /quizRoom (new route)`  section seamlessly.
3. Design creativity is in your hands this time; craft a component that complements the Create Room section.
4. Integrate the Join Room component to the right side of the Create Room component within the home section.
5. Leverage hooks, props, and the Ant Design library for an enhanced UI.
6. Explore suitable UI inspiration from platforms like Dribbble or Behance.

**🚀 Implementation Details:**

**# Component Destination**: `src/components/joinRoom.jsx`
**# Route Placement**: `/home` route, to the right side of the center, adjacent to the Create Room component.

Your dedication to delivering quality work will not go unnoticed.

**🔗 Claim Your Contribution:**
If you are ready to take on this impactful task, please comment to claim it.

**Comment by TheDivineAurora** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by 0xShiiro** [comment]
Claim

**Comment by Nandinig24** [comment]
Claim

**Comment by shashankpatil28** [comment]
@Codefreakpriyanshu, it's a relatively straightforward task. Kindly ensure completion by tomorrow morning. Thank you.

**Comment by shashankpatil28** [comment]
@Codefreakpriyanshu  kindly review the issue once more. I have made some minute updates to the details.

**Comment by shashankpatil28** [comment]
@Codefreakpriyanshu I have to unassign you from the issue due to no response.

**Comment by TheDivineAurora** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by chiragmalik2612** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by shashankpatil28** [comment]
@kushal7201 the task must be completed by Sunday morning. happy Coding.

**Comment by kushal7201** [comment]
@shashankpatil28  I'll try my best
