### ISSUE TITLE
Embark on the Sign-In 

### ISSUE THREAD

**Issue by shashankpatil28** [opencodeiiita/GrepIt-Frontend#41]
### We've got an exciting task ahead! We've successfully set up the sign-up feature, and now it's time to tackle the sign-in component.

**🔧 Tasks:**

1. Create the sign-in component, similar to the sign-up one, but with username and password input boxes.
2. Check the APIendpoint.md in the grepIt-backend repo for detailed API endpoints.
3. Use the right hooks to smoothly integrate necessary props into the Sign-in component.
4. Concentrate on improving the Sign-in component exclusively.
5. Make sure to handle errors in the implementation.

**⚙️ Details Matter:**

> Keep all changes confined to the Sign-in component.
> Thanks for contributing to Hitch's collaborative journey! 🚀 Feel free to comment to claim the issue.

**Comment by TheDivineAurora** [comment]
claim

**Comment by shashankpatil28** [comment]
Hey @TheDivineAurora, please ensure the task is completed by Sunday evening. Quality work is always appreciated here. Thanks!

**Comment by TheDivineAurora** [comment]
ok

**Comment by chiragmalik2612** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by Mannxxx** [comment]
Claim
