### ISSUE TITLE
Level Up: Quiz Room Edition 

### ISSUE THREAD

**Issue by shashankpatil28** [opencodeiiita/GrepIt-Frontend#42]
### We're diving into a key GrepIt feature—the Quiz Room. Here's the rundown:

**🔧 Tasks:**

1. Create /quizRoom route, splitting the page into two parts.
2. Left side: Question component showing the question and options.
3. Right side: Leaderboard (already developed).
4. Add checkboxes, and success/failure colors on options. Implement success logic on question submit (backend connection later).
5. Include the 'Previous' and 'Next' question buttons at the bottom of the question component.
6. Populate the question component with dummy data for the time being.

> Check the various questions type components here

https://preview.themeforest.net/item/qzain-multiple-test-quiz-templates/full_screen_preview/44534188?_ga=2.169794725.583462586.1703274531-611163126.1683378128

**Claim this issue by commenting. Thanks!**

**Comment by TheDivineAurora** [comment]
claim

**Comment by WadadParker** [comment]
Claim

**Comment by shashankpatil28** [comment]
@TheDivineAurora I can't assign more than one issue in the same repo currently.

**Comment by chiragmalik2612** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by Mannxxx** [comment]
claim

**Comment by WadadParker** [comment]
@bhupesh98 Please unassign me from this issue, I have not been able to give time to this, let sm1 else do this.

**Comment by chiragmalik2612** [comment]
@bhupesh98  i want to work on it , assign me plz

**Comment by bhupesh98** [comment]
> @bhupesh98  i want to work on it , assign me plz

Assigned👍🏻

**Comment by bhupesh98** [comment]
This issue is up for the claim again!
I expect this time to be requested by a person who can complete the task as it has been pending for long.

**Comment by Rohit-110** [comment]
Claim

**Comment by rnavaneeth992** [comment]
Claim

**Comment by AmanGxpta** [comment]
Claim

**Comment by Apoorv012** [comment]
claim

**Comment by bhupesh98** [comment]
@Rohit-110 assigning you! You can refer to previous chats with chirag Malik on discord and if you have some other queries or resources required, kindly get it cleared as soon as possible.

**Comment by bhupesh98** [comment]
@Rohit-110 updates on this task?
And let me know your discord ID.

**Comment by Rohit-110** [comment]
@bhupesh98  still working on this task.
discord id rohit_46

**Comment by Rohit-110** [comment]
@bhupesh98 please unassign me, i will take more time

**Comment by bhupesh98** [comment]
@Rohit-110 In case you need time based on the work you did, you can request to extend your time. Do you still want to quit working on this issue?

**Comment by rnavaneeth992** [comment]
@bhupesh98 I can work on this issue

**Comment by bhupesh98** [comment]
> @bhupesh98 I can work on this issue 

Wait till the afternoon, as he feels he can submit a PR by today. Upon reviewing the progress I'll decide whether to assign it to you or let him have the time.

**Comment by rnavaneeth992** [comment]
> > @bhupesh98 I can work on this issue
> 
> Wait till the afternoon, as he feels he can submit a PR by today. Upon reviewing the progress I'll decide whether to assign it to you or let him have the time.

Ok Sure Thanks

**Comment by bhupesh98** [comment]
@rnavaneeth992 assigning you, You can work on this but make sure to do it as soon as possible, you may be required to clean up the logic as to configure theme we need to have antd designs as much as possible.
Just work or Quiz.jsx without editing Leaderboard.jsx as it is being prepared by myself.
