### ISSUE TITLE
 Global Theme Implementation with Ant Design (Antd) ConfigProvider

### ISSUE THREAD

**Issue by bhupesh98** [opencodeiiita/GrepIt-Frontend#46]
Embark on a mission to enhance the visual appeal and consistency of our project by implementing a global theme using Ant Design's (Antd) `ConfigProvider`. This task involves seamlessly integrating Antd's styling across the entire application, and converting default React components to Antd components for a streamlined and theme-ready UI.

## Task:
Implement a global theme using Antd ConfigProvider, ensuring a cohesive and visually pleasing design throughout the project. Convert default React components to Antd components for effortless theme implementation on various pages and components.

## Details:
1. Antd ConfigProvider Setup:
    - Configure Antd ConfigProvider at the root level of your application i.e. [App.jsx](https://github.com/opencodeiiita/GrepIt-Frontend/blob/master/src/App.jsx).
    - Set up a custom theme using Antd's theming capabilities. Customize the primary color, typography, and any other relevant styles.

2. Global Theme Integration:
    - Apply the Antd ConfigProvider to encapsulate the entire application, ensuring the global theme is consistently applied.
    - Verify that the global theme aligns with the project's design requirements and enhances user experience.
 
3. Convert Default React Components:
    - Identify default React components used across different pages and components.
    - Replace these default components with corresponding Antd components to leverage the unified theme.
    - Ensure that the Antd components seamlessly integrate with existing functionality and styling.
  
4. Theme Implementation:
    - Test the theme implementation on various pages to guarantee a visually cohesive and harmonized user interface.
    - Verify that Antd components maintain compatibility with your project's requirements and functionality.

Claim this task and enhance the project's visual aesthetics with a unified theme. Feel free to reach out if you have any questions or need assistance during the process.

**Comment by TheDivineAurora** [comment]
claim

**Comment by Apoorv012** [comment]
claim

**Comment by bhupesh98** [comment]
@TheDivineAurora Assigned!

Reference for ConfigProvider:
https://ant.design/docs/react/customize-theme

Components Overview:
https://ant.design/components/overview/
