### ISSUE TITLE
Recommendation: Cool animating background

### ISSUE THREAD

**Issue by bhupesh98** [opencodeiiita/GrepIt-Frontend#48]
Find and recommend a cool continuously animating background preferably in dark and blue theme. 

Apply this animated bg on [Home.jsx](https://github.com/opencodeiiita/GrepIt-Frontend/blob/main/src/pages/Home.jsx) and [Quiz.jsx](https://github.com/opencodeiiita/GrepIt-Frontend/blob/main/src/pages/Quiz.jsx) and make a pull request on main branch. Best PR will be selected and good ones will be given partial points. Points can increase or decrease based on coolness of the animated bg.

PS: Make sure to not disturb other components while applying it.
As this is a competitive issue, you don't need to claim.

🚧 Deadline: 6th Jan 12pm

**Comment by TheDivineAurora** [comment]
claim

**Comment by k7aditya** [comment]
what is the deadline of this task?

**Comment by bhupesh98** [comment]
> what is the deadline of this task?

By tomorrow afternoon

**Comment by kushal7201** [comment]
Claim

**Comment by bhupesh98** [comment]
> Claim

@kushal7201  This is a competitive issue, you can start working on this task.

**Comment by Mannxxx** [comment]
claim
