### ISSUE TITLE
Colors Unleashed: Transforming the Visual Realm with our Enchanting Theme!

### ISSUE THREAD

**Issue by bhupesh98** [opencodeiiita/GrepIt-Frontend#49]
## Task:
Configure the theme in the project using the provided `ConfigProvider` in the codebase. Choose appropriate theme colors and adjust them in the `theme.ts` file where the theme configuration is defined. Some components require special attention and should be configured individually or by component type rather than token type.

## Details:
1) Theme Configuration:
Update the [theme.ts](https://github.com/opencodeiiita/GrepIt-Frontend/blob/main/src/utils/theme.ts) file in the codebase to reflect the chosen theme colors. Adjust properties such as primaryColor, secondaryColor, headerBg etc and text based on the identified color scheme.

2) Component Configuration:
Identify components that require special configuration. For each of these components, ensure that the theme colors are adjusted individually or by component type.

>[!WARNING]
> Avoid using Tailwind CSS for changing colours as it is hard to look for in the codebase when modifying.  

3) Exclusion of `Quiz.jsx` Page:
Ensure that the [Quiz.jsx](https://github.com/opencodeiiita/GrepIt-Frontend/blob/main/src/pages/Quiz.jsx) page remains unaffected by the theme configurations, i.e. no extra configuration for that file. Review how the theme is applied globally or selectively to exclude this page from the theme adjustments.

You can also provide theme colours ( *`descriptive`* as per material theme standards) in comments or discord and if it looks good on the page, you will get bonus points despite the fact whomsoever this issue has been assigned. It's requested to the assignee to feel free to try out the theme colours suggested by other participants.

**Comment by ajay484** [comment]
claim

**Comment by TheDivineAurora** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by bhupesh98** [comment]
As @TheDivineAurora has been given Issue #50, @kushal7201 I am assigning you this task

**Comment by Mannxxx** [comment]
claim

**Comment by bhupesh98** [comment]
This issue is up for claim again!

**Comment by TheDivineAurora** [comment]
claim

**Comment by Apoorv012** [comment]
claim

**Comment by Rohit-110** [comment]
Claim

**Comment by bhupesh98** [comment]
> claim

@TheDivineAurora Assigned!

**Comment by kushal7201** [comment]
Claim
