### ISSUE TITLE
Your Profile: Stylish User Data display and Seamless Navigation

### ISSUE THREAD

**Issue by bhupesh98** [opencodeiiita/GrepIt-Frontend#50]
## Task:
Implement an engaging profile page on new route `/profile` using Ant Design (antd) components, showcasing key user statistics. Leverage Ant Design's UI library to create a visually appealing layout with components such as username, profile photo, email, and pending rooms.

## Details:
1) Ant Design Integration:
Ensure Ant Design is integrated into the project. Install the necessary Ant Design components and import them into the profile page file.

2) Profile Page Layout:
Create a layout for the profile page using Ant Design components. Utilize components such as Layout, Card, Avatar, and others for a clean and organized design.
User Stats Display:

3) Display the following user data on the profile page:
    - Username
    - Profile photo
    - Email
4) Pending Rooms Section:
Implement a section for displaying pending rooms. For each pending room, include the following details:
    - Room ID
    - Room Name
    - Join Button
5) Update User Profile:
Implement functionality to update user statistics. Provide a user-friendly interface for users to edit their username, upload a new profile photo, and update their email.

6) NavBar as Layout.Header:
Utilize NavBar component as the Layout.Header for a consistent navigation experience. Customize the navigation bar to include links to different sections of the profile page.

7) Responsive Design:
Ensure that the profile page is responsive and provides a seamless experience across different devices and screen sizes.

**Comment by TheDivineAurora** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by bhupesh98** [comment]
@TheDivineAurora Assigning this to you.

**Comment by Mannxxx** [comment]
claim
