### ISSUE TITLE
Integrate Frontend and Backend for Sign-In and Sign-Up Pages

### ISSUE THREAD

**Issue by bhupesh98** [opencodeiiita/GrepIt-Frontend#55]
## Details:

1) Review Backend Documentation:
Go through the provided backend documentation thoroughly provided in [API Documentation](https://github.com/opencodeiiita/GrepIt-Backend/blob/main/API_ENDPOINTS.md).
Understand the API endpoints, request methods, and required parameters for sign-in and sign-up functionalities.

2) Integration technique:
Integrate the sign-in & sign-up with backend maintaining tokens in localstorage for remembering user. Fields sent in json body must be verified and tested with the running backend in [Live Backend](https://grep-it-api.onrender.com/) (Let us know if backend is inactive or not responding).

>[!NOTE]
> `useAuth` context hook must be used to maintain login credentials.

PS: As the contribution period is ending, we expect PRs as soon as possible.

**Comment by kushal7201** [comment]
Claim

**Comment by Apoorv012** [comment]
claim

**Comment by bhupesh98** [comment]
> Claim

@kushal7201 Assigned!
