### ISSUE TITLE
Wrap the application with useAuth

### ISSUE THREAD

**Issue by bhupesh98** [opencodeiiita/GrepIt-Frontend#56]
## Details:
Wrap the profile , quiz page with `useAuth` context hook if not authorized, using AntD design [Result Component](https://ant.design/components/result) to disallow user to enter that page.

**Comment by Apoorv012** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by TheDivineAurora** [comment]
Claim

**Comment by bhupesh98** [comment]
> claim

@Apoorv012 Assigned!

**Comment by bhupesh98** [comment]
This issue is up for claim again!

**Comment by Rohit-110** [comment]
Claim

**Comment by bhupesh98** [comment]
> Claim 

@Rohit-110 assigned!
