### ISSUE TITLE
Creating and Connecting the room!

### ISSUE THREAD

**Issue by bhupesh98** [opencodeiiita/GrepIt-Frontend#57]
## Details:
1) Backend Review:
Understand backend documentation for leaderboard and real-time question endpoints provided in [API Documentation](https://github.com/opencodeiiita/GrepIt-Backend/blob/main/API_ENDPOINTS.md) and [Socket Events](https://github.com/opencodeiiita/GrepIt-Backend/blob/main/SOCKET_EVENTS.md).

2) Frontend Setup:
Ensure frontend project structure is organized and ready for integration.

3) Utilize Socket Events:
    - Make suggested requests to create a room, (Scheduling the quiz is not yet implemented on backend but just sent it to backend via a query parameter after encoding in URL). Upon creating the room, it must navigate to quiz room.
    - Join Room form via room code must also be integrated.
    
PS: Feel free to reach out on discord incase of any confusion.

**Comment by Apoorv012** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by TheDivineAurora** [comment]
claim

**Comment by bhupesh98** [comment]
Since you all have been assigned issues here, I can't assign you more. 😄

**Comment by Apoorv012** [comment]
claim

**Comment by Apoorv012** [comment]
claim

**Comment by VatsalBhuva11** [comment]
@Apoorv012 assigned. note that you have 2 hours left.
