### ISSUE TITLE
Make the Quiz Alive - Integrate Leaderboard and Real-time Questions

### ISSUE THREAD

**Issue by bhupesh98** [opencodeiiita/GrepIt-Frontend#58]
## Details: 
1) Backend Review:
Understand backend documentation for leaderboard and real-time question endpoints provided in [API Documentation](https://github.com/opencodeiiita/GrepIt-Backend/blob/main/API_ENDPOINTS.md) and [Socket Events](https://github.com/opencodeiiita/GrepIt-Backend/blob/main/SOCKET_EVENTS.md).

2) Frontend Setup:
Ensure frontend project structure is organized and ready for integration.

3) API Configuration:
Set up constants for leaderboard and WebSocket URLs based on backend documentation.

4) WebSocket for Questions:
    - Implement WebSocket connection for real-time question updates and leaderboard.
    - Update quiz interface dynamically as new questions arrive.

5) Utilize the lifecycle methods
    - Use countdown timer. Send the response to the question as soon as the timer ends (latest option that is chosen) and reset it again as soon as the new question arrives from backend.

>[!NOTE]
> Make sure to handle the errors. Feel free to ask on discord incase of confusion.

**Comment by Apoorv012** [comment]
claim

**Comment by Rohit-110** [comment]
Claim

**Comment by TheDivineAurora** [comment]
claim

**Comment by bhupesh98** [comment]
> Claim

Since @Apoorv012 wants to work on this issue instead of #56, you can be assigned there.

**Comment by bhupesh98** [comment]
> > Claim
> 
> @Rohit-110 Since @Apoorv012 wants to work on this issue instead of #56, you can be assigned there.

**Comment by bhupesh98** [comment]
> Claim

 @Rohit-110 Since @Apoorv012 wants to work on this issue instead of #56, you can be assigned there.
