### ISSUE TITLE
Navbar Modeling 

### ISSUE THREAD

**Issue by shashankpatil28** [opencodeiiita/GrepIt-Frontend#7]
### Navbar Modeling in GrepIt

**We've got a thrilling task for you – bring GrepIt's vision to life by crafting The Navbar Component. Detailed instructions are provided below.**

**#Task Details:**

Your goal is to make a Navbar with the given Details,

**#Details**

1. The Navbar must be responsive for most devices.
2. The Navbar must have GrepIt Name on the left side. and Search Input on the right side only. No extra content.
3. Complete white with Shadow: large and 75 viewport width on the right Top of the website 
4. Mandatory use of Tailwind CSS. For additional benefits, incorporate Ant Design.

**#Time**: `24 hours`

**Take Reference from this ->**

![navbar Grepit](https://github.com/opencodeiiita/GrepIt-Frontend/assets/122175701/d0d5e6d5-07e4-4e4d-87d2-502c252fd9c0)

> NOTE: The component must be made in src/components/navbar/navbar.jsx and must be placed in app router having path '/home'

comment to claim the issue.

**Comment by Apoorv012** [comment]
claim

**Comment by CodinJack** [comment]
claim

**Comment by PranavBansal21** [comment]
Claim

**Comment by Nivedh-Biju** [comment]
claim

**Comment by rebornstar1** [comment]
claim

**Comment by shashankpatil28** [comment]
@CodinJack, @PranavBansal21, and  @Nivedh-Biju issue is claimed already. More issues to come in the Event. Stay tuned and Happy contributing.

**Comment by shashankpatil28** [comment]
@Apoorv012 kindly read the issue details properly and work accordingly in the meantime. quality work within time will be appriciated. If any doubts, feel free to ask on Discord.

**Comment by Nandinig24** [comment]
Claim

**Comment by rnavaneeth992** [comment]
claim
